{"cells":[{"cell_type":"markdown","execution_count":null,"metadata":{"tags":[]},"outputs":[],"source":["# TSG056 - Kubectl fails with No connection could be made because the target machine actively refused it\n","\n","The `kubectl` command line interface fails with:\n","\n","\u003e kubectl get nodes\n","\u003e\n","\u003e Unable to connect to the server: dial tcp 10.91.136.142:6443:\n","\u003e connectex: No connection could be made because the target machine\n","\u003e actively refused it.\n","\n","## Description\n","\n","This is usually because the `.kube/config` file has become\n","misconfigured. On Windows the config file is usually in the\n","`c:\\users\\%username%\\.kube` folder. On Linux the config file is usually\n","in the `~/src/.kube` folder.\n","\n","This issue often happens if the Kubernetes cluster has been reset, and\n","the local `.kube\\config` is now out of date. To resolve this issue, try\n","making a copy of he current `.kube\\config` file, and then copy the\n","`~/.kube/config` from the Kubernetes master instance to the local\n","machine (as `.kube\\config`)."]}],"nbformat":4,"nbformat_minor":5,"metadata":{"kernelspec":{"name":"python3","display_name":"Python 3"},"pansop":{"related":"","test":{"strategy":"","types":null,"disable":{"reason":"","workitems":null,"types":null}},"target":{"current":"","final":""},"internal":{"parameters":null,"symlink":false},"timeout":"0"},"language_info":{"codemirror_mode":"{ Name: \"\", Version: \"\"}","file_extension":"","mimetype":"","name":"","nbconvert_exporter":"","pygments_lexer":"","version":""},"widgets":[]}}